ALTER TABLE "BlogPost"
  ADD COLUMN IF NOT EXISTS "meta_title" TEXT,
  ADD COLUMN IF NOT EXISTS "meta_description" TEXT,
  ADD COLUMN IF NOT EXISTS "focus_keyword" TEXT,
  ADD COLUMN IF NOT EXISTS "og_title" TEXT,
  ADD COLUMN IF NOT EXISTS "og_description" TEXT,
  ADD COLUMN IF NOT EXISTS "og_image_url" TEXT,
  ADD COLUMN IF NOT EXISTS "og_image_path" TEXT,
  ADD COLUMN IF NOT EXISTS "canonical_url" TEXT,
  ADD COLUMN IF NOT EXISTS "no_index" BOOLEAN NOT NULL DEFAULT false;
