// prisma/seed-data.ts
// 20 realistic AI courses + users, categories, hero slides, etc.

export const seedCategories = [
  { id: "cat-1", name: "Machine Learning", slug: "machine-learning", icon: "Brain", color: "#00d4ff", description: "Core ML algorithms, theory & practice" },
  { id: "cat-2", name: "Deep Learning", slug: "deep-learning", icon: "Cpu", color: "#7c3aed", description: "Neural networks & advanced architectures" },
  { id: "cat-3", name: "Natural Language Processing", slug: "nlp", icon: "MessageSquare", color: "#ec4899", description: "Text understanding & generation" },
  { id: "cat-4", name: "Computer Vision", slug: "computer-vision", icon: "Eye", color: "#10b981", description: "Image recognition & video analysis" },
  { id: "cat-5", name: "AI Engineering", slug: "ai-engineering", icon: "Code2", color: "#f59e0b", description: "Deploy & scale AI in production" },
  { id: "cat-6", name: "Generative AI", slug: "generative-ai", icon: "Sparkles", color: "#06b6d4", description: "LLMs, diffusion models & creative AI" },
  { id: "cat-7", name: "Data Science", slug: "data-science", icon: "BarChart3", color: "#8b5cf6", description: "Analytics, visualization & insights" },
  { id: "cat-8", name: "Robotics & AI", slug: "robotics", icon: "Bot", color: "#ef4444", description: "Autonomous systems & reinforcement learning" },
];

export const seedCourses = [
  {
    id: "course-1",
    title: "Complete Machine Learning Mastery",
    slug: "complete-machine-learning-mastery",
    description: "Master machine learning from scratch to production. Build real-world projects with scikit-learn, XGBoost, and deploy to cloud platforms. Covers regression, classification, clustering, ensemble methods, and model optimization.",
    shortDescription: "From zero to ML engineer — master algorithms, tools & deployment",
    thumbnailUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=340&fit=crop",
    categoryId: "cat-1",
    categoryName: "Machine Learning",
    level: "BEGINNER" as const,
    price: 89,
    originalPrice: 199,
    isFree: false,
    isFeatured: true,
    isTrending: true,
    isNew: false,
    totalDuration: 2940, // minutes
    totalLessons: 142,
    totalStudents: 48320,
    rating: 4.8,
    totalRatings: 6821,
    tags: ["Python", "scikit-learn", "XGBoost", "ML Algorithms"],
    whatYouLearn: ["Build & tune ML models", "Handle real datasets", "Deploy to production", "Model monitoring"],
    instructorName: "Dr. Sarah Chen",
    instructorAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-2",
    title: "Deep Learning with PyTorch & Lightning",
    slug: "deep-learning-pytorch-lightning",
    description: "Build state-of-the-art neural networks with PyTorch and PyTorch Lightning. From perceptrons to transformers — implement CNNs, RNNs, attention mechanisms, and train on GPUs. Production-ready patterns included.",
    shortDescription: "Neural networks, transformers & production ML with PyTorch",
    thumbnailUrl: "https://images.unsplash.com/photo-1676277791608-ac54525aa94d?w=600&h=340&fit=crop",
    categoryId: "cat-2",
    categoryName: "Deep Learning",
    level: "INTERMEDIATE" as const,
    price: 119,
    originalPrice: 249,
    isFree: false,
    isFeatured: true,
    isTrending: true,
    isNew: false,
    totalDuration: 3420,
    totalLessons: 178,
    totalStudents: 31240,
    rating: 4.9,
    totalRatings: 4502,
    tags: ["PyTorch", "Deep Learning", "CNNs", "Transformers", "GPU"],
    whatYouLearn: ["PyTorch fundamentals", "CNN/RNN architectures", "Transformers from scratch", "Multi-GPU training"],
    instructorName: "Andrei Volkov",
    instructorAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-3",
    title: "LLM Engineering: Build Production AI Apps",
    slug: "llm-engineering-production",
    description: "Learn to build powerful applications with GPT-4, Claude, and open-source LLMs. Master prompt engineering, RAG systems, LangChain, vector databases, and fine-tuning. Ship real AI products used by thousands.",
    shortDescription: "GPT-4, Claude, LangChain, RAG & fine-tuning — ship AI products",
    thumbnailUrl: "https://images.unsplash.com/photo-1675557009483-d0cb609fa8d5?w=600&h=340&fit=crop",
    categoryId: "cat-6",
    categoryName: "Generative AI",
    level: "INTERMEDIATE" as const,
    price: 149,
    originalPrice: 299,
    isFree: false,
    isFeatured: true,
    isTrending: true,
    isNew: true,
    totalDuration: 2880,
    totalLessons: 156,
    totalStudents: 22100,
    rating: 4.9,
    totalRatings: 3820,
    tags: ["GPT-4", "LangChain", "RAG", "Vector DB", "Fine-tuning"],
    whatYouLearn: ["Prompt engineering mastery", "Build RAG pipelines", "Fine-tune open models", "Deploy AI APIs"],
    instructorName: "Dr. Mia Patel",
    instructorAvatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-4",
    title: "Computer Vision with OpenCV & YOLO",
    slug: "computer-vision-opencv-yolo",
    description: "From image processing to real-time object detection. Master OpenCV, build custom YOLO models, implement face recognition, and deploy vision systems for production. Includes 15 hands-on projects.",
    shortDescription: "Object detection, face recognition & real-time vision systems",
    thumbnailUrl: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=600&h=340&fit=crop",
    categoryId: "cat-4",
    categoryName: "Computer Vision",
    level: "INTERMEDIATE" as const,
    price: 99,
    originalPrice: 199,
    isFree: false,
    isFeatured: false,
    isTrending: true,
    isNew: false,
    totalDuration: 2160,
    totalLessons: 118,
    totalStudents: 18920,
    rating: 4.7,
    totalRatings: 2930,
    tags: ["OpenCV", "YOLO", "Computer Vision", "Object Detection"],
    whatYouLearn: ["Image processing", "Object detection", "Face recognition", "Video analysis"],
    instructorName: "Carlos Mendez",
    instructorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-5",
    title: "NLP with Transformers & Hugging Face",
    slug: "nlp-transformers-huggingface",
    description: "Comprehensive NLP course using the Hugging Face ecosystem. Build sentiment analyzers, text summarizers, translation systems, and chatbots. Fine-tune BERT, GPT, and T5 for custom tasks.",
    shortDescription: "BERT, GPT, T5 & Hugging Face — NLP from theory to production",
    thumbnailUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&h=340&fit=crop",
    categoryId: "cat-3",
    categoryName: "NLP",
    level: "ADVANCED" as const,
    price: 129,
    originalPrice: 249,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: false,
    totalDuration: 2700,
    totalLessons: 134,
    totalStudents: 14560,
    rating: 4.8,
    totalRatings: 2150,
    tags: ["BERT", "GPT", "Hugging Face", "NLP", "Transformers"],
    whatYouLearn: ["Transformer architecture", "Fine-tune LLMs", "Build NLP pipelines", "Deploy NLP APIs"],
    instructorName: "Dr. Emma Wilson",
    instructorAvatar: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-6",
    title: "AI for Everyone: Non-Technical Bootcamp",
    slug: "ai-for-everyone-non-technical",
    description: "No coding required. Understand how AI works, use AI tools in your workflow, make informed AI strategy decisions, and lead AI projects. Perfect for business leaders, product managers, and creative professionals.",
    shortDescription: "Understand & leverage AI — no coding needed",
    thumbnailUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&h=340&fit=crop",
    categoryId: "cat-7",
    categoryName: "Data Science",
    level: "BEGINNER" as const,
    price: 59,
    originalPrice: 129,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: false,
    totalDuration: 900,
    totalLessons: 52,
    totalStudents: 42000,
    rating: 4.6,
    totalRatings: 7820,
    tags: ["AI Strategy", "No-Code AI", "ChatGPT", "Business AI"],
    whatYouLearn: ["AI fundamentals", "Use AI tools", "AI project management", "AI ethics"],
    instructorName: "James Thornton",
    instructorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-7",
    title: "Reinforcement Learning & Autonomous Agents",
    slug: "reinforcement-learning-autonomous-agents",
    description: "Master reinforcement learning from Q-learning to PPO and SAC. Build game-playing agents, robotic controllers, and autonomous systems. Includes OpenAI Gym, Stable Baselines3, and real robotic simulation.",
    shortDescription: "Q-learning, PPO, autonomous agents & robotic simulation",
    thumbnailUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=600&h=340&fit=crop",
    categoryId: "cat-8",
    categoryName: "Robotics & AI",
    level: "ADVANCED" as const,
    price: 139,
    originalPrice: 279,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    totalDuration: 3120,
    totalLessons: 162,
    totalStudents: 8340,
    rating: 4.8,
    totalRatings: 1240,
    tags: ["Reinforcement Learning", "PPO", "OpenAI Gym", "Robotics"],
    whatYouLearn: ["RL algorithms", "Build game agents", "Robotic control", "Multi-agent systems"],
    instructorName: "Dr. Riku Tanaka",
    instructorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-8",
    title: "Stable Diffusion & Generative Art Mastery",
    slug: "stable-diffusion-generative-art",
    description: "Create stunning AI-generated art and images. Master Stable Diffusion, ControlNet, LoRA fine-tuning, and build your own image generation APIs. Learn prompt engineering for visual AI and monetize your skills.",
    shortDescription: "Stable Diffusion, ControlNet, LoRA & generative art workflows",
    thumbnailUrl: "https://images.unsplash.com/photo-1686191128892-3b37add4c844?w=600&h=340&fit=crop",
    categoryId: "cat-6",
    categoryName: "Generative AI",
    level: "BEGINNER" as const,
    price: 79,
    originalPrice: 159,
    isFree: false,
    isFeatured: false,
    isTrending: true,
    isNew: true,
    totalDuration: 1680,
    totalLessons: 94,
    totalStudents: 29800,
    rating: 4.7,
    totalRatings: 4560,
    tags: ["Stable Diffusion", "Generative AI", "LoRA", "ControlNet"],
    whatYouLearn: ["SD fundamentals", "Advanced prompting", "LoRA training", "ComfyUI workflows"],
    instructorName: "Aria Zhang",
    instructorAvatar: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-9",
    title: "MLOps: Production ML Systems at Scale",
    slug: "mlops-production-ml-systems",
    description: "Design, build, and maintain ML systems in production. Master MLflow, Kubeflow, Docker, Kubernetes for ML, feature stores, model monitoring, and CI/CD for ML. Real case studies from top tech companies.",
    shortDescription: "MLflow, Kubeflow, CI/CD & monitoring for production ML",
    thumbnailUrl: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&h=340&fit=crop",
    categoryId: "cat-5",
    categoryName: "AI Engineering",
    level: "ADVANCED" as const,
    price: 159,
    originalPrice: 319,
    isFree: false,
    isFeatured: true,
    isTrending: false,
    isNew: false,
    totalDuration: 3600,
    totalLessons: 186,
    totalStudents: 11240,
    rating: 4.9,
    totalRatings: 1820,
    tags: ["MLOps", "MLflow", "Kubeflow", "Docker", "Kubernetes"],
    whatYouLearn: ["ML pipelines", "Model monitoring", "Feature stores", "ML CI/CD"],
    instructorName: "David Kim",
    instructorAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-10",
    title: "Data Science with Python: Complete Bootcamp",
    slug: "data-science-python-complete-bootcamp",
    description: "The most comprehensive data science course. Master NumPy, Pandas, Matplotlib, Seaborn, SQL, statistics, A/B testing, and storytelling with data. Build 12 real-world projects with actual datasets.",
    shortDescription: "Pandas, NumPy, SQL, stats & data storytelling — complete bootcamp",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&h=340&fit=crop",
    categoryId: "cat-7",
    categoryName: "Data Science",
    level: "BEGINNER" as const,
    price: 69,
    originalPrice: 149,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: false,
    totalDuration: 2520,
    totalLessons: 128,
    totalStudents: 68900,
    rating: 4.7,
    totalRatings: 12400,
    tags: ["Python", "Pandas", "NumPy", "Data Science", "SQL"],
    whatYouLearn: ["Data wrangling", "Statistical analysis", "Data visualization", "A/B testing"],
    instructorName: "Dr. Lisa Park",
    instructorAvatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-11",
    title: "AI Agents & Autonomous Workflows with LangGraph",
    slug: "ai-agents-langgraph",
    description: "Build sophisticated AI agents that can browse the web, write and execute code, manage files, and complete multi-step tasks autonomously. Master LangGraph, CrewAI, AutoGen, and custom agent architectures.",
    shortDescription: "LangGraph, CrewAI & AutoGen — build autonomous AI agents",
    thumbnailUrl: "https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=600&h=340&fit=crop",
    categoryId: "cat-6",
    categoryName: "Generative AI",
    level: "ADVANCED" as const,
    price: 169,
    originalPrice: 339,
    isFree: false,
    isFeatured: true,
    isTrending: true,
    isNew: true,
    totalDuration: 2760,
    totalLessons: 144,
    totalStudents: 9820,
    rating: 4.9,
    totalRatings: 1560,
    tags: ["AI Agents", "LangGraph", "CrewAI", "AutoGen"],
    whatYouLearn: ["Agent design patterns", "Tool use & function calling", "Multi-agent orchestration", "Production agents"],
    instructorName: "Marcus Reed",
    instructorAvatar: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-12",
    title: "Graph Neural Networks for Real-World Problems",
    slug: "graph-neural-networks",
    description: "Master GNNs for social networks, drug discovery, recommendation systems, and fraud detection. Implement GCN, GAT, GraphSAGE with PyTorch Geometric and Deep Graph Library. 10 industry-grade projects.",
    shortDescription: "GCN, GAT, GraphSAGE — GNNs for recommendations, biology & fraud",
    thumbnailUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=340&fit=crop",
    categoryId: "cat-2",
    categoryName: "Deep Learning",
    level: "ADVANCED" as const,
    price: 149,
    originalPrice: 299,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    totalDuration: 2880,
    totalLessons: 148,
    totalStudents: 4820,
    rating: 4.8,
    totalRatings: 720,
    tags: ["GNN", "Graph Learning", "PyTorch Geometric", "Drug Discovery"],
    whatYouLearn: ["Graph fundamentals", "GNN architectures", "Molecule property prediction", "Fraud detection GNNs"],
    instructorName: "Dr. Priya Sharma",
    instructorAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-13",
    title: "AI for Healthcare: Clinical ML Applications",
    slug: "ai-healthcare-clinical-ml",
    description: "Apply AI to real medical challenges. Build diagnostic models for medical imaging, predict patient outcomes, analyze clinical notes with NLP, and navigate healthcare regulations. Includes MIMIC-III dataset projects.",
    shortDescription: "Medical imaging, clinical NLP & patient outcome prediction",
    thumbnailUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&h=340&fit=crop",
    categoryId: "cat-4",
    categoryName: "Computer Vision",
    level: "ADVANCED" as const,
    price: 179,
    originalPrice: 359,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: false,
    totalDuration: 3240,
    totalLessons: 168,
    totalStudents: 6340,
    rating: 4.8,
    totalRatings: 960,
    tags: ["Healthcare AI", "Medical Imaging", "Clinical NLP", "MIMIC"],
    whatYouLearn: ["Medical image segmentation", "EHR data analysis", "Regulatory compliance", "Clinical validation"],
    instructorName: "Dr. James Okafor",
    instructorAvatar: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-14",
    title: "Time Series Forecasting with ML & Deep Learning",
    slug: "time-series-forecasting",
    description: "Master time series analysis for finance, energy, retail, and IoT. Implement ARIMA, Prophet, LSTM, Temporal Fusion Transformers, and N-BEATS. Build forecasting systems that handle seasonality, trends, and anomalies.",
    shortDescription: "ARIMA, Prophet, LSTM & TFT — forecasting for finance & IoT",
    thumbnailUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=340&fit=crop",
    categoryId: "cat-1",
    categoryName: "Machine Learning",
    level: "INTERMEDIATE" as const,
    price: 109,
    originalPrice: 219,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: false,
    totalDuration: 2340,
    totalLessons: 122,
    totalStudents: 12840,
    rating: 4.7,
    totalRatings: 1940,
    tags: ["Time Series", "LSTM", "Prophet", "Finance AI"],
    whatYouLearn: ["Statistical forecasting", "DL for time series", "Anomaly detection", "Production deployment"],
    instructorName: "Sophie Laurent",
    instructorAvatar: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-15",
    title: "Prompt Engineering: The Complete Playbook",
    slug: "prompt-engineering-complete-playbook",
    description: "The definitive guide to prompt engineering. Master chain-of-thought, few-shot learning, system prompts, adversarial prompting, and automated prompt optimization. Works with GPT-4, Claude, Gemini, and open models.",
    shortDescription: "Chain-of-thought, few-shot & automated prompt optimization",
    thumbnailUrl: "https://images.unsplash.com/photo-1673187648778-e4c41d87c8d5?w=600&h=340&fit=crop",
    categoryId: "cat-3",
    categoryName: "NLP",
    level: "BEGINNER" as const,
    price: 49,
    originalPrice: 99,
    isFree: false,
    isFeatured: false,
    isTrending: true,
    isNew: false,
    totalDuration: 960,
    totalLessons: 58,
    totalStudents: 38200,
    rating: 4.7,
    totalRatings: 6820,
    tags: ["Prompt Engineering", "GPT-4", "Claude", "Chain-of-Thought"],
    whatYouLearn: ["Prompt design patterns", "Advanced techniques", "Multi-modal prompts", "Prompt optimization"],
    instructorName: "Ryan Torres",
    instructorAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-16",
    title: "Federated Learning & Privacy-Preserving AI",
    slug: "federated-learning-privacy-ai",
    description: "Build AI systems that learn from distributed data without centralizing sensitive information. Master federated learning with PySyft, differential privacy, secure aggregation, and deploy FL systems for healthcare and finance.",
    shortDescription: "PySyft, differential privacy & federated learning for regulated industries",
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&h=340&fit=crop",
    categoryId: "cat-5",
    categoryName: "AI Engineering",
    level: "ADVANCED" as const,
    price: 159,
    originalPrice: 319,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    totalDuration: 2640,
    totalLessons: 138,
    totalStudents: 3820,
    rating: 4.9,
    totalRatings: 580,
    tags: ["Federated Learning", "Privacy AI", "Differential Privacy", "PySyft"],
    whatYouLearn: ["FL system design", "Differential privacy", "Secure aggregation", "Regulatory compliance"],
    instructorName: "Dr. Kenji Watanabe",
    instructorAvatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-17",
    title: "AI Ethics, Safety & Responsible Development",
    slug: "ai-ethics-safety-responsible-development",
    description: "Navigate the complex landscape of AI ethics. Understand bias, fairness, transparency, alignment, and safety. Build ethical AI systems, conduct audits, and develop governance frameworks for responsible AI deployment.",
    shortDescription: "Bias, fairness, alignment & governance for responsible AI",
    thumbnailUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&h=340&fit=crop",
    categoryId: "cat-7",
    categoryName: "Data Science",
    level: "ALL_LEVELS" as const,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isFeatured: false,
    isTrending: false,
    isNew: false,
    totalDuration: 1200,
    totalLessons: 68,
    totalStudents: 89400,
    rating: 4.8,
    totalRatings: 14200,
    tags: ["AI Ethics", "Responsible AI", "Fairness", "AI Safety"],
    whatYouLearn: ["Bias auditing", "Fairness metrics", "AI governance", "Safety evaluation"],
    instructorName: "Dr. Amara Johnson",
    instructorAvatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-18",
    title: "Edge AI: Deploy Models on Mobile & IoT",
    slug: "edge-ai-mobile-iot",
    description: "Deploy AI to devices with limited compute. Master TensorFlow Lite, ONNX, CoreML, model quantization, pruning, and knowledge distillation. Build real AR apps, smart cameras, and IoT AI systems.",
    shortDescription: "TFLite, ONNX, CoreML & quantization — AI on mobile & embedded",
    thumbnailUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=340&fit=crop",
    categoryId: "cat-5",
    categoryName: "AI Engineering",
    level: "INTERMEDIATE" as const,
    price: 119,
    originalPrice: 239,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    totalDuration: 2160,
    totalLessons: 112,
    totalStudents: 7640,
    rating: 4.7,
    totalRatings: 1180,
    tags: ["Edge AI", "TFLite", "CoreML", "Model Optimization", "IoT"],
    whatYouLearn: ["Model optimization", "Mobile deployment", "IoT AI", "Quantization & pruning"],
    instructorName: "Natasha Ivanova",
    instructorAvatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-19",
    title: "Multimodal AI: Vision, Language & Audio Together",
    slug: "multimodal-ai-vision-language-audio",
    description: "Build AI systems that understand and generate across modalities. Implement CLIP, Flamingo, GPT-4V, Whisper, and DALL-E. Create apps that see, hear, read, and respond. The future of AI is multimodal.",
    shortDescription: "CLIP, GPT-4V, Whisper & DALL-E — build multimodal AI systems",
    thumbnailUrl: "https://images.unsplash.com/photo-1619472032094-eadb7ec01655?w=600&h=340&fit=crop",
    categoryId: "cat-6",
    categoryName: "Generative AI",
    level: "ADVANCED" as const,
    price: 169,
    originalPrice: 339,
    isFree: false,
    isFeatured: false,
    isTrending: true,
    isNew: true,
    totalDuration: 3000,
    totalLessons: 158,
    totalStudents: 5420,
    rating: 4.9,
    totalRatings: 820,
    tags: ["Multimodal AI", "CLIP", "GPT-4V", "Whisper", "DALL-E"],
    whatYouLearn: ["Vision-language models", "Audio-text models", "Cross-modal retrieval", "Build multimodal apps"],
    instructorName: "Dr. Oliver Chen",
    instructorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
  {
    id: "course-20",
    title: "AI Product Management: From Idea to Launch",
    slug: "ai-product-management",
    description: "Bridge the gap between AI capability and business value. Define AI product vision, work with ML teams, measure model performance as a PM, navigate AI limitations, and lead AI product launches. For PMs moving into AI.",
    shortDescription: "Define, ship & measure AI products — the PM's complete guide",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=340&fit=crop",
    categoryId: "cat-7",
    categoryName: "Data Science",
    level: "INTERMEDIATE" as const,
    price: 89,
    originalPrice: 179,
    isFree: false,
    isFeatured: false,
    isTrending: false,
    isNew: true,
    totalDuration: 1440,
    totalLessons: 82,
    totalStudents: 11200,
    rating: 4.6,
    totalRatings: 1860,
    tags: ["AI Product", "Product Management", "AI Strategy", "ML Teams"],
    whatYouLearn: ["AI opportunity sizing", "ML team collaboration", "AI metrics & KPIs", "AI product launches"],
    instructorName: "Christina Blake",
    instructorAvatar: "https://images.unsplash.com/photo-1504763342341-1d4af2aa54c4?w=100&h=100&fit=crop&crop=face",
    language: "English",
  },
];

export const seedHeroSlides = [
  {
    id: "slide-1",
    title: "Learn AI. Build the Future.",
    subtitle: "The World's Most Advanced AI Education Platform",
    description: "Join 500,000+ learners mastering Machine Learning, LLMs, and AI Engineering with hands-on projects and personalized AI coaching.",
    imageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=1400&h=600&fit=crop",
    ctaText: "Start Free Today",
    ctaLink: "/courses",
    isActive: true,
    order: 0,
  },
  {
    id: "slide-2",
    title: "Master LLM Engineering",
    subtitle: "Build with GPT-4, Claude & Open Models",
    description: "Ship real AI products. Learn RAG, fine-tuning, agents, and production deployment from engineers who've done it at scale.",
    imageUrl: "https://images.unsplash.com/photo-1675557009483-d0cb609fa8d5?w=1400&h=600&fit=crop",
    ctaText: "Explore LLM Courses",
    ctaLink: "/courses?category=generative-ai",
    isActive: true,
    order: 1,
  },
  {
    id: "slide-3",
    title: "AI Career Transformation",
    subtitle: "From Any Background to AI Engineer in 6 Months",
    description: "Personalized learning roadmaps, 1-on-1 AI mentoring, and career support. 92% of our graduates land AI roles within 6 months.",
    imageUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=1400&h=600&fit=crop",
    ctaText: "Get Your Roadmap",
    ctaLink: "/signup",
    isActive: true,
    order: 2,
  },
];

export const seedAnnouncements = [
  { id: "ann-1", text: "🔥 Flash Sale: 70% off all courses this weekend only", link: "/courses", linkText: "Shop Now", isActive: true },
  { id: "ann-2", text: "🎉 New Course: AI Agents & Autonomous Workflows — Early Bird Pricing Live!", link: "/courses/ai-agents-langgraph", linkText: "Enroll Now", isActive: true },
];

export const seedTestimonials = [
  {
    id: "t-1",
    name: "Kwame Asante",
    role: "ML Engineer @ Google",
    avatar: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=80&h=80&fit=crop&crop=face",
    rating: 5,
    text: "This platform completely transformed my career. I went from a data analyst to an ML Engineer at Google in 8 months. The projects are incredibly realistic.",
    courseCompleted: "Complete Machine Learning Mastery",
    country: "🇬🇭 Ghana",
  },
  {
    id: "t-2",
    name: "Priya Mehta",
    role: "AI Research Lead @ Microsoft",
    avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=80&h=80&fit=crop&crop=face",
    rating: 5,
    text: "The LLM Engineering course is hands-down the best resource on the internet for building production AI. I reference the materials constantly at work.",
    courseCompleted: "LLM Engineering: Build Production AI Apps",
    country: "🇮🇳 India",
  },
  {
    id: "t-3",
    name: "Diego Ramirez",
    role: "Computer Vision Engineer @ Tesla",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    rating: 5,
    text: "I built a working YOLO-based system for my portfolio after the Computer Vision course. Got hired at Tesla 3 weeks after completing it. Insane ROI.",
    courseCompleted: "Computer Vision with OpenCV & YOLO",
    country: "🇲🇽 Mexico",
  },
  {
    id: "t-4",
    name: "Amara Osei",
    role: "AI Product Manager @ Stripe",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&crop=face",
    rating: 5,
    text: "As a PM, I was intimidated by AI. This platform made it approachable. Now I confidently lead our AI team and make better product decisions. Invaluable.",
    courseCompleted: "AI Product Management: From Idea to Launch",
    country: "🇬🇭 Ghana",
  },
];

export const seedBlogPosts = [
  {
    id: "blog-1",
    title: "The State of LLMs in 2025: What Every Engineer Must Know",
    slug: "state-of-llms-2025",
    excerpt: "From GPT-4o to Claude 3.5 and Gemini Ultra — a comprehensive technical breakdown of where large language models stand today and what's coming next.",
    coverImage: "https://images.unsplash.com/photo-1675557009483-d0cb609fa8d5?w=600&h=340&fit=crop",
    authorName: "Dr. Mia Patel",
    tags: ["LLMs", "AI Research", "GPT-4"],
    publishedAt: "2025-01-15",
    readTime: "12 min read",
  },
  {
    id: "blog-2",
    title: "Building Production RAG Systems: Lessons from 50+ Deployments",
    slug: "production-rag-systems-lessons",
    excerpt: "We analyzed 50 production RAG deployments. Here's what actually works, what fails, and the architecture patterns that scale.",
    coverImage: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=600&h=340&fit=crop",
    authorName: "Marcus Reed",
    tags: ["RAG", "LLM Engineering", "Production AI"],
    publishedAt: "2025-01-08",
    readTime: "18 min read",
  },
  {
    id: "blog-3",
    title: "AI Jobs Report 2025: Skills That Actually Get You Hired",
    slug: "ai-jobs-report-2025-skills",
    excerpt: "We analyzed 10,000 AI job postings. These are the exact skills hiring managers are looking for — and the ones that command the highest salaries.",
    coverImage: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=340&fit=crop",
    authorName: "Christina Blake",
    tags: ["Careers", "AI Jobs", "Skills"],
    publishedAt: "2025-01-02",
    readTime: "10 min read",
  },
];

export const seedSubscriptionPlans = [
  {
    id: "plan-1",
    name: "Free",
    slug: "free",
    description: "Free Plan - all free courses + certificates",
    price: 0,
    yearlyPrice: null,
    currency: "USD",
    features: [
      "All free courses",
      "Certificates of completion",
      "Mobile and desktop learning access",
    ],
    coursesIncluded: ["FREE"],
    isPopular: false,
    isActive: true,
  },
  {
    id: "plan-2",
    name: "Pro",
    slug: "pro",
    description: "Access to ALL courses + priority support + early access",
    price: 79,
    yearlyPrice: 790,
    currency: "USD",
    features: [
      "Access to ALL courses",
      "Priority support",
      "Early access to new releases",
    ],
    coursesIncluded: ["ALL"],
    isPopular: true,
    isActive: true,
  },
  {
    id: "plan-3",
    name: "Teams",
    slug: "teams",
    description: "Everything in Pro + admin dashboard & progress tracking",
    price: 199,
    yearlyPrice: 1990,
    currency: "USD",
    features: [
      "Everything in Pro",
      "Admin dashboard",
      "Team progress tracking",
    ],
    coursesIncluded: ["ALL"],
    isPopular: false,
    isActive: true,
  },
];

export const seedUsers = [
  {
    id: "user-admin",
    email: "admin@ailearning.com",
    name: "Admin User",
    role: "ADMIN" as const,
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    totalCourses: 0,
    totalStudents: 0,
  },
];

// Stats for admin dashboard
export const seedAdminStats = {
  totalRevenue: 284920,
  monthlyRevenue: 38420,
  totalStudents: 48320,
  activeStudents: 12840,
  totalCourses: 20,
  completionRate: 68,
  avgRating: 4.78,
  revenueByMonth: [
    { month: "Aug", revenue: 22400 },
    { month: "Sep", revenue: 28900 },
    { month: "Oct", revenue: 31200 },
    { month: "Nov", revenue: 29800 },
    { month: "Dec", revenue: 34100 },
    { month: "Jan", revenue: 38420 },
  ],
  topCategories: [
    { name: "Generative AI", students: 18200, percentage: 37 },
    { name: "Machine Learning", students: 14800, percentage: 30 },
    { name: "Deep Learning", students: 9600, percentage: 20 },
    { name: "Data Science", students: 5720, percentage: 13 },
  ],
  recentOrders: [
    { id: "ord-1", student: "Kwame Asante", course: "LLM Engineering", amount: 149, date: "2025-01-15", status: "COMPLETED" },
    { id: "ord-2", student: "Priya Mehta", course: "Deep Learning Mastery", amount: 119, date: "2025-01-15", status: "COMPLETED" },
    { id: "ord-3", student: "Diego Ramirez", course: "Computer Vision", amount: 99, date: "2025-01-14", status: "COMPLETED" },
    { id: "ord-4", student: "Sarah Kim", course: "MLOps", amount: 159, date: "2025-01-14", status: "PENDING" },
    { id: "ord-5", student: "Alex Thompson", course: "AI Agents", amount: 169, date: "2025-01-13", status: "COMPLETED" },
  ],
};

